spring:
  application:
    name: child-bank
  config:
    activate:
      on-profile: no-gui

json:
  template-path: data_template.json5
  data-path: ./data.json

logging:
  level:
    com.seg83.childbank: DEBUG

gui:
  enabled: false